"""added created_by columns in necessary fields

Revision ID: 52988e6d946a
Revises: 9b80568feb19
Create Date: 2025-08-05 10:54:42.754304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52988e6d946a'
down_revision: Union[str, Sequence[str], None] = '9b80568feb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('attendances', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attendances', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('prescriptions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'prescriptions', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'created_by')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'created_by')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'created_by')
    # ### end Alembic commands ###
