"""added timezone stamp to datetime field in doctorslot model

Revision ID: 766d00ec99e3
Revises: dbb74d727885
Create Date: 2025-08-07 12:21:28.559291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '766d00ec99e3'
down_revision: Union[str, Sequence[str], None] = 'dbb74d727885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_slots', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('doctor_slots', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_slots', 'end_time',
               existing_type=sa.DateTime(timezone=False),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('doctor_slots', 'start_time',
               existing_type=sa.DateTime(timezone=False),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
