"""added rbac endpoint table

Revision ID: ab1bf589786d
Revises: 52988e6d946a
Create Date: 2025-08-05 12:47:02.539131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1bf589786d'
down_revision: Union[str, Sequence[str], None] = '52988e6d946a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('methods', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoints')
    # ### end Alembic commands ###
