"""add notes field to available slots model

Revision ID: dbb74d727885
Revises: ab1bf589786d
Create Date: 2025-08-06 10:37:51.304577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb74d727885'
down_revision: Union[str, Sequence[str], None] = 'ab1bf589786d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_slots', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_slots', 'notes')
    # ### end Alembic commands ###
