from app.models.base_model import BaseModel
from app.models.appointments import Appointment
from app.models.attendance import Attendance
from app.models.doctor_slots import DoctorSlot
from app.models.doctor import Doctor
from app.models.patients import Patient
from app.models.prescriptions import Prescription
from app.models.users import User
from app.models.rbac import Endpoint